print('Hello world!')
print('I LOVE YOU')
print("Enablers")
print("UNDP")
print(5 + 5)
TODAY = ("Data governace law")
print(TODAY)
UICT = ('The institute of technology but we are progressing day and night, kindly join us')
print(UICT)
DATA = ("National and implement integrated and interoperable ")
print(DATA)
UNGLOBAL = ('How students can tap into this coversation and we see thje way we can develop until the next coming years')
print(UNGLOBAL)
ICT =('National ict innovation hub, kindly always attend and learn with us, such that we can try to analyse the faeture of technlogy')
print(ICT)
TECHWIZ = ('MTN uganda')
print(TECHWIZ)
AR = ('Continue commit5ting, u never know what this will hold for us all, take your time')
print(AR)
PANEL = ('Discussion, Hello all of us, glad that we are in our house')
print(PANEL)
