print('Hello world!')
print('I LOVE YOU')
print("Enablers")
print("UNDP")
print(5 + 5)
TODAY = ("Data governace law")
print(TODAY)
UICT = ('The institute of technfology but we are progressing day and night, kindly join us')
print(UICT)
DATA = ("National and implement integrated and interoperable ")
print(DATA)
UNGLOBAL = ('How students can tap into this coversationa and we see thje way we can develop until the next coming years')
print(UNGLOBAL)
ICT =('National ict innovation hub, kindly always attend and learn with us, such taht we can try to analyse the faeture of technlogy')
print(ICT)
